name: Sample Workflow

on: [workflow_dispatch, push]

jobs:
  amd_job:
    name: Amd Job
    runs-on: ubuntu-latest
    steps:
      - name: Run commands
        run: |
          uname -a
          arch
          sudo cat /etc/group

          echo $USER
  power_job:
    name: Power Job
    runs-on: ubuntu-18.04-ppc64le
    steps:
      - name: Run commands
        run: |
          uname -a
          arch
          echo $USER
          sudo cat /etc/group
