name: Sample Workflow

on: [workflow_dispatch, push, pull_request]

jobs:
  test_job:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04-ppc64le]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Run commands
        run: |
          uname -a
          arch
          echo "sleeping for 5 minutes..."
          sleep 5m
          echo "wake up..."
