name: Sample Workflow

on: [workflow_dispatch, push]

jobs:
  test_job:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04-ppc64le, ubuntu-20.04-ppc64le]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Run commands
        run: |
          uname -a
          arch
          sudo cat /etc/group

          echo $USER
  power_job:
    name: Power Job
    runs-on: [ubuntu-18.04-ppc64le, ubuntu-20.04-ppc64le]
    steps:
      - name: Run commands
        run: |
          uname -a
          arch
          echo $USER
          sudo cat /etc/group
